# -*- coding: utf-8 -*-
"""Training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LhWA7aDBV1_AHPyIlWR47hYSlNkTmmHN
"""

# ==========================================================
# 1) IMPORTS
# ==========================================================
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

import seaborn as sns
import matplotlib.pyplot as plt
import joblib

sns.set(style="whitegrid")

# ==========================================================
# 2) LOAD DATA
# ==========================================================
df = pd.read_csv("/content/sample_data/GYM.csv")
print("✅ Loaded Dataset")
print(df.head())

# ==========================================================
# 3) NORMALIZE COLUMN NAMES
# ==========================================================
df.columns = (
    df.columns.str.lower()
              .str.strip()
              .str.replace(" ", "_")
              .str.replace("-", "_")
)

print("\n🔹 Normalized Columns:", df.columns.tolist())

# ==========================================================
# 4) SELECT RELEVANT COLUMNS + CLEAN
# ==========================================================
df = df[["gender", "goal", "bmi_category", "exercise_schedule"]].dropna()

# Apply consistent formatting
df["gender"] = df["gender"].str.title()
df["goal"] = df["goal"].str.lower().str.replace("_", " ")
df["bmi_category"] = df["bmi_category"].str.title()

# Remove swimming-related workouts (noisy / unsupported)
df = df[~df["exercise_schedule"].str.contains("swimming", case=False, na=False)]

print(f"✅ Rows After Cleaning: {len(df)}")
df.head()

# ==========================================================
# 5) VISUALIZATIONS
# ==========================================================
plt.figure(figsize=(6,4))
sns.countplot(data=df, x="goal", hue="goal", legend=False, palette="magma")
plt.title("🏋️ Distribution of Fitness Goals")
plt.xticks(rotation=20)
plt.show()

plt.figure(figsize=(6,4))
sns.countplot(data=df, x="bmi_category", hue="bmi_category", legend=False, palette="cool")
plt.title("⚖️ BMI Category Distribution")
plt.xticks(rotation=20)
plt.show()

pivot = pd.crosstab(df.bmi_category, df.goal)
plt.figure(figsize=(6,4))
sns.heatmap(pivot, annot=True, cmap="crest")
plt.title("🔥 BMI vs Goal Relationship")
plt.show()

# ==========================================================
# 6) LABEL ENCODING
# ==========================================================
encoders = {}
for col in df.columns:
    encoders[col] = LabelEncoder()
    df[col] = encoders[col].fit_transform(df[col])

X = df.drop("exercise_schedule", axis=1)
y = df["exercise_schedule"]

# ==========================================================
# 7) TRAIN / TEST + SCALING
# ==========================================================
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)

# ==========================================================
# 8) TRAIN MODEL
# ==========================================================
model = RandomForestClassifier(n_estimators=200, random_state=42)
model.fit(X_train, y_train)
pred = model.predict(X_test)

acc = accuracy_score(y_test, pred)
print(f"\n🎯 Model Accuracy: {acc:.2f}")

print("\n📊 Classification Report:")
print(classification_report(y_test, pred))

# ==========================================================
# 9) CONFUSION MATRIX
# ==========================================================
plt.figure(figsize=(5,4))
sns.heatmap(confusion_matrix(y_test, pred), annot=True, cmap="Purples", fmt="d")
plt.title("🧠 Confusion Matrix")
plt.show()

# ==========================================================
# 10) FEATURE IMPORTANCE
# ==========================================================
plt.figure(figsize=(5,4))
sns.barplot(x=model.feature_importances_, y=X.columns, palette="viridis")
plt.title("🔍 Feature Importance")
plt.show()

# ==========================================================
# 11) SAVE MODEL FOR FLUTTER USE
# ==========================================================
joblib.dump(model, "fitness_recommender.pkl")
joblib.dump(scaler, "scaler.pkl")
joblib.dump(encoders, "label_encoders.pkl")

print("\n✅✅ Model, Scaler, and Encoders Saved! Ready for Flutter AI integration.")
